# Git Aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gb='git branch'
alias gl='git log --oneline --graph --decorate'
alias gp='git push'
alias gpl='git pull'
alias gd='git diff'

# Additional aliases based on your common usage
alias gcam='git cam'
alias gst='git st'
alias gsts='git st -s'
alias glol='git lol'
alias grm='git rebasemain'
alias gstash='git staash'
alias gundo='git undo'
alias gpl='git please'
alias gcmd='git commadd'
alias gcp='git cherry-pick'